import { Heading, Box, Text, Image } from "@chakra-ui/react";
import React from "react";

export const AdvantagesofspiralRoundDucts = () => {
  return (
    <Box mt={{ base: "30px", lg: "250px" }}>
      <Box>
        <Heading
          mb={{ base: "-35px", lg: "-20px" }}
          textAlign={{ base: "center", lg: "center" }}
          color="#ec2330"
          fontSize={{ base: "20px", lg: "25px" }}
          fontFamily="poppins"
          mr={{ base: "-720px", lg: "0px" }}
        >
          ADVANTAGES OF SPIRAL ROUND OVAL DUCT
        </Heading>

        <Box
          display={{ base: "flex", lg: "flex" }}
          flexDir={{ base: "column", lg: "row" }}
          p={{ base: "30px", lg: "30px" }}
          justifyContent={{ base: "center", lg: "center" }}
          ml={{ base: "100px", lg: "0px" }}
        >
          <Box m="15px" className="scale-up-center-on-hover">
            <Box
              border="solid #cccccc 2px"
              borderTop='solid #f44336 4px'
              h="330px"
              w="400px"
              borderRadius="5px"
              boxShadow='inner'  bg='white'
            
            >
              <Box>
                <Box h="20px" w="100px" pt="8px" ml="150px">
                  <Image src="./Dustductgimg.jpg" alt="Durabilityimg" />
                </Box>
                <Heading
                  textAlign="center"
                  mt="90px"
                  fontSize="25px"
                  fontFamily="poppins"
                >
                  Durability
                </Heading>
              </Box>
              <Box>
                <Text p="20px" textAlign="justify">
                  Spiral round ducts are commonly made from galvanized steel or
                  other durable materials, ensuring long-term reliability and
                  resistance to corrosion and wear.
                </Text>
              </Box>
            </Box>
          </Box>

          <Box m="15px" className="scale-up-center-on-hover">
            <Box
              border="solid #cccccc 2px"
              borderTop='solid #f44336 4px'
              h="330px"
              w="400px"
              borderRadius="5px"
              boxShadow='inner'  bg='white'
            >
              <Box>
                <Box h="20px" w="150px" pt="12px" ml="140px">
                  <Image src="./CustomiZationimg.png" alt="CustomiZationimg" />
                </Box>

                <Heading
                  textAlign="center"
                  mt="90px"
                  fontSize="25px"
                  fontFamily="poppins"
                >
                  Customization
                </Heading>
              </Box>
              <Box>
                <Text p="20px" textAlign="justify">
                  Spiral round ducts can be customized to meet specific project
                  requirements in terms of size, length, and fittings. This
                  flexibility allows for precise design and installation in
                  various HVAC applications.
                </Text>
              </Box>
            </Box>
          </Box>

          <Box m="15px" className="scale-up-center-on-hover">
            <Box
              border="solid #cccccc 2px"
              borderTop='solid #f44336 4px'
              h="330px"
              w="400px"
              borderRadius="5px"
              boxShadow='inner'  bg='white'
            >
              <Box>
                <Box h="20px" w="90px" pt="15px" ml="160px">
                  <Image
                    src="./Sound Attenuationimage.jpeg"
                    alt="Ductfabsoundimg"
                  />
                </Box>
                <Heading
                  textAlign="center"
                  mt="90px"
                  fontSize="25px"
                  fontFamily="poppins"
                >
                  Noise Reduction
                </Heading>
              </Box>
              <Box>
                <Text p="20px" textAlign="justify">
                  The smooth, streamlined design of round ducts can help reduce
                  noise generated by the HVAC system, contributing to quieter
                  operation in commercial and residential settings.
                </Text>
              </Box>
            </Box>
          </Box>
        </Box>

        <Box
          display={{ base: "flex", lg: "flex" }}
          flexDir={{ base: "column", lg: "row" }}
          p={{ base: "30px", lg: "30px" }}
          justifyContent={{ base: "center", lg: "center" }}
          ml={{ base: "540px", lg: "0px" }}
          mt={{ base: "-1140px", lg: "-60px" }}
        >
          <Box m="15px" className="scale-up-center-on-hover">
            <Box
              border="solid #cccccc 2px"
              borderTop='solid #f44336 4px'
              h="330px"
              w="400px"
              borderRadius="5px"
              boxShadow='inner'  bg='white'
            >
              <Box>
                <Box h="20px" w="70px" pt="15px" ml="150px">
                  <Image src="./Ductfabspace.png" alt="Ductfabspace" />
                </Box>
                <Heading
                  textAlign="center"
                  mt="90px"
                  fontSize="25px"
                  fontFamily="poppins"
                >
                  Space Efficiency
                </Heading>
              </Box>
              <Box>
                <Text p="20px" textAlign="justify">
                  Round ducts are space-efficient and can be installed in tight
                  or constrained spaces where square or rectangular ducts may
                  not fit as easily.
                </Text>
              </Box>
            </Box>
          </Box>

          <Box m="15px" className="scale-up-center-on-hover">
            <Box
              border="solid #cccccc 2px"
              borderTop='solid #f44336 4px'
              h="330px"
              w="400px"
              borderRadius="5px"
              boxShadow='inner' bg='white'
            >
              <Box>
                <Box h="20px" w="130px" pt="12px" ml="140px">
                  <Image src="./Hygiene.png" alt="Hygieneimg" />
                </Box>
                <Heading
                  textAlign="center"
                  mt="90px"
                  fontSize="25px"
                  fontFamily="poppins"
                >
                  Hygiene
                </Heading>
              </Box>
              <Box>
                <Text p="20px" textAlign="justify">
                  The design of flat oval ducts makes them relatively easy to
                  clean and maintain, which is important for maintaining good
                  indoor air quality and hygiene standards.
                </Text>
              </Box>
            </Box>
          </Box>

          <Box m="15px" className="scale-up-center-on-hover">
            <Box
              border="solid #cccccc 2px"
              borderTop='solid #f44336 4px'
              h="330px"
              w="400px"
              borderRadius="5px"
              boxShadow='inner'  bg='white'
            >
              <Box>
                <Box h="20px" w="90px" pt="13px" ml="150px">
                  <Image src="./EasyInstallationimages.png" alt="Ductfabair" />
                </Box>
                <Heading
                  textAlign="center"
                  mt="90px"
                  fontSize="25px"
                  fontFamily="poppins"
                >
                  Easy Installation
                </Heading>
              </Box>
              <Box>
                <Text p="20px" textAlign="justify">
                  The spiral-seam construction and lightweight nature of these
                  ducts make them relatively easy to install. This can save time
                  and labor costs during the installation process.
                </Text>
              </Box>
            </Box>
          </Box>
        </Box>
      </Box>
    </Box>
  );
};
